---
- name: Configure Common Prereqs
  hosts: all
  become: true
  roles:
    - common

- name: Configure Control Plane
  hosts: control_plane
  become: true
  roles:
    - control-plane
  tags: configure_control_plane

- name: Configure Worker Nodes
  hosts: workers
  become: true
  roles:
    - worker
  tags: join_workers
