---
- name: Check if node is already joined
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kube_config

- name: Retrieve Join Command from Control Plane
  command: kubeadm token create --print-join-command
  register: join_command_raw
  delegate_to: "{{ groups['control_plane'][0] }}"
  run_once: true
  when: kube_config.stat.exists == false

- debug:
    msg: "{{ join_command_raw.stdout }}"
  when: kube_config.stat.exists == false

- name: Join Cluster
  command: "{{ join_command_raw.stdout }}"
  args:
    creates: /etc/kubernetes/kubelet.conf
  when: kube_config.stat.exists == false
