---
- name: Check if node is already joined
  ansible.builtin.stat:
    path: /etc/kubernetes/kubelet.conf
  register: worker_kube_config

- name: Retrieve Join Command from Control Plane
  ansible.builtin.command: kubeadm token create --print-join-command
  register: worker_join_command_raw
  delegate_to: "{{ groups['control_plane'][0] }}"
  run_once: true
  changed_when: false
  when: not worker_kube_config.stat.exists

- name: Debug Join Command
  ansible.builtin.debug:
    msg: "{{ worker_join_command_raw.stdout }}"
  when: not worker_kube_config.stat.exists

- name: Join Cluster
  ansible.builtin.command: "{{ worker_join_command_raw.stdout }}"
  args:
    creates: /etc/kubernetes/kubelet.conf
  when: not worker_kube_config.stat.exists
